export default [
  {
    id: "7e8",
    status: "Unfilled",
    address: "193 Del Sol Avenue",
    currentCapacity: 65,
    MaxCapacity: 147,
  },
  {
    id: "174",
    status: "Unfilled",
    address: "49617 Reinke Court",
    currentCapacity: 8,
    MaxCapacity: 178,
  },
  {
    id: "0aa",
    status: "Unfilled",
    address: "206 Lake View Alley",
    currentCapacity: 70,
    MaxCapacity: 152,
  },
  {
    id: "11d",
    status: "Unfilled",
    address: "078 Heath Crossing",
    currentCapacity: 7,
    MaxCapacity: 494,
  },
  {
    id: "797",
    status: "Overloaded",
    address: "7 Susan Crossing",
    currentCapacity: 93,
    MaxCapacity: 434,
  },
  {
    id: "242",
    status: "Overloaded",
    address: "5281 Crescent Oaks Court",
    currentCapacity: 35,
    MaxCapacity: 463,
  },
  {
    id: "adf",
    status: "Overloaded",
    address: "883 Arapahoe Avenue",
    currentCapacity: 48,
    MaxCapacity: 388,
  },
  {
    id: "269",
    status: "Overloaded",
    address: "7485 Gina Road",
    currentCapacity: 85,
    MaxCapacity: 370,
  },
  {
    id: "09b",
    status: "Unfilled",
    address: "55 Hazelcrest Lane",
    currentCapacity: 32,
    MaxCapacity: 283,
  },
  {
    id: "a99e",
    status: "Unfilled",
    address: "3076 Independence Circle",
    currentCapacity: 12,
    MaxCapacity: 428,
  },
  {
    id: "0dbe",
    status: "Unfilled",
    address: "2339 Forest Run Avenue",
    currentCapacity: 33,
    MaxCapacity: 368,
  },
  {
    id: "932",
    status: "Overloaded",
    address: "6 Crescent Oaks Street",
    currentCapacity: 34,
    MaxCapacity: 363,
  },
  {
    id: "e69f",
    status: "Unfilled",
    address: "3 Delaware Park",
    currentCapacity: 2,
    MaxCapacity: 176,
  },
  {
    id: "2f4f",
    status: "Overloaded",
    address: "1132 Mendota Center",
    currentCapacity: 11,
    MaxCapacity: 355,
  },
  {
    id: "eb0ae",
    status: "Unfilled",
    address: "9935 Donald Street",
    currentCapacity: 48,
    MaxCapacity: 369,
  },
  {
    id: "464abf",
    status: "Unfilled",
    address: "9937 Dryden Park",
    currentCapacity: 21,
    MaxCapacity: 346,
  },
  {
    id: "c120b7",
    status: "Overloaded",
    address: "405 Village Avenue",
    currentCapacity: 78,
    MaxCapacity: 404,
  },
  {
    id: "f7",
    status: "Overloaded",
    address: "20717 Saint Paul Way",
    currentCapacity: 41,
    MaxCapacity: 254,
  },
  {
    id: "ba93",
    status: "Unfilled",
    address: "66 La Follette Drive",
    currentCapacity: 72,
    MaxCapacity: 480,
  },
  {
    id: "dc2f",
    status: "Unfilled",
    address: "5911 Walton Avenue",
    currentCapacity: 60,
    MaxCapacity: 348,
  },
];
