export default [
  {
    id: "1460",
    type: "troller",
    status: "Unavailable",
    weight: 243,
    capacity: 190,
    fuel_consumption: 61,
    username: "cchiommienti0",
  },
  {
    id: "d026218",
    type: "truck",
    status: "Progress",
    weight: 295,
    capacity: 266,
    fuel_consumption: 31,
  },
  {
    id: "7e",
    type: "troller",
    status: "Available",
    weight: 113,
    capacity: 119,
    fuel_consumption: 37,
    username: "lbowick1",
  },
  {
    id: "28a",
    type: "truck",
    status: "Unavailable",
    weight: 71,
    capacity: 215,
    fuel_consumption: 98,
    username: "mmccaughren2",
  },
  {
    id: "6bc0",
    type: "truck",
    status: "Unavailable",
    weight: 231,
    capacity: 226,
    fuel_consumption: 61,
    username: "bskillington3",
  },
  {
    id: "bd77c5fe",
    type: "troller",
    status: "Available",
    weight: 170,
    capacity: 194,
    fuel_consumption: 79,
    username: "pchisman4",
  },
  {
    id: "75",
    type: "troller",
    status: "Progress",
    weight: 273,
    capacity: 215,
    fuel_consumption: 43,
    username: "rtorri5",
  },
  {
    id: "4c31f9",
    type: "truck",
    status: "Available",
    weight: 168,
    capacity: 205,
    fuel_consumption: 92,
    username: "sbolter6",
  },
  {
    id: "b7",
    type: "truck",
    status: "Available",
    weight: 264,
    capacity: 362,
    fuel_consumption: 40,
    username: "dcurphey7",
  },
  {
    id: "8be9f",
    type: "truck",
    status: "Available",
    weight: 293,
    capacity: 353,
    fuel_consumption: 30,
    username: "hmatkin8",
  },
  {
    id: "172",
    type: "truck",
    status: "Progress",
    weight: 174,
    capacity: 193,
    fuel_consumption: 58,
    username: "wmills9",
  },
  {
    id: "f8bf",
    type: "troller",
    status: "Available",
    weight: 123,
    capacity: 289,
    fuel_consumption: 66,
    username: "afilbya",
  },
  {
    id: "b",
    type: "truck",
    status: "Unavailable",
    weight: 256,
    capacity: 170,
    fuel_consumption: 69,
    username: "awornhamb",
  },
  {
    id: "62a2",
    type: "troller",
    status: "Available",
    weight: 167,
    capacity: 476,
    fuel_consumption: 87,
    username: "vminetc",
  },
  {
    id: "8069",
    type: "truck",
    status: "Available",
    weight: 165,
    capacity: 359,
    fuel_consumption: 49,
    username: "mstronoughd",
  },
  {
    id: "5dea",
    type: "truck",
    status: "Progress",
    weight: 180,
    capacity: 200,
    fuel_consumption: 36,
    username: "ccaldicote",
  },
  {
    id: "4",
    type: "truck",
    status: "Available",
    weight: 242,
    capacity: 183,
    fuel_consumption: 88,
    username: "jcornhillf",
  },
  {
    id: "997d",
    type: "troller",
    status: "Unavailable",
    weight: 296,
    capacity: 149,
    fuel_consumption: 39,
    username: "kmcmurtyrg",
  },
  {
    id: "9426",
    type: "truck",
    status: "Available",
    weight: 129,
    capacity: 339,
    fuel_consumption: 44,
    username: "menticknaph",
  },
  {
    id: "122",
    type: "troller",
    status: "Progress",
    weight: 283,
    capacity: 106,
    fuel_consumption: 98,
    username: "hspoerli",
  },
];
